"""add top genres and moods

Revision ID: 99c141131bb8
Revises: e81221d5fb0e
Create Date: 2026-03-30 11:41:05.990984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c141131bb8'
down_revision: Union[str, None] = 'e81221d5fb0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('top_genres', sa.JSON(), nullable=True))
    op.add_column('analysis_results', sa.Column('top_moods', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'top_moods')
    op.drop_column('analysis_results', 'top_genres')
    # ### end Alembic commands ###
